name: expensetrackerapp
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"  # Correction du format de la version du SDK

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.2  # Suppression des guillemets inutiles
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^15.1.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4

  flutter_bloc: ^8.1.6


  # The following adds the Cupertino Icons font to your application.

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/monyapplogo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/monyapplogo.png