// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0yw8ectTTe7tOuEp9PYYTzfjelpqOoGc',
    appId: '1:349288109231:web:55c65029c3b88f03c0305a',
    messagingSenderId: '349288109231',
    projectId: 'expensetrackerapp-d4ad0',
    authDomain: 'expensetrackerapp-d4ad0.firebaseapp.com',
    storageBucket: 'expensetrackerapp-d4ad0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-XmSTv7i3MFawmQxBbUKBG2RcxTkPsgg',
    appId: '1:349288109231:android:62c24d82570e2caac0305a',
    messagingSenderId: '349288109231',
    projectId: 'expensetrackerapp-d4ad0',
    storageBucket: 'expensetrackerapp-d4ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM6dVW5aV6ga1FTc-cPgtYocjLcgWUH60',
    appId: '1:349288109231:ios:df0e76a78806e7bfc0305a',
    messagingSenderId: '349288109231',
    projectId: 'expensetrackerapp-d4ad0',
    storageBucket: 'expensetrackerapp-d4ad0.firebasestorage.app',
    iosBundleId: 'com.example.expensetrackerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM6dVW5aV6ga1FTc-cPgtYocjLcgWUH60',
    appId: '1:349288109231:ios:df0e76a78806e7bfc0305a',
    messagingSenderId: '349288109231',
    projectId: 'expensetrackerapp-d4ad0',
    storageBucket: 'expensetrackerapp-d4ad0.firebasestorage.app',
    iosBundleId: 'com.example.expensetrackerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0yw8ectTTe7tOuEp9PYYTzfjelpqOoGc',
    appId: '1:349288109231:web:c9367f4d21d8a2a1c0305a',
    messagingSenderId: '349288109231',
    projectId: 'expensetrackerapp-d4ad0',
    authDomain: 'expensetrackerapp-d4ad0.firebaseapp.com',
    storageBucket: 'expensetrackerapp-d4ad0.firebasestorage.app',
  );

}